[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "discord-py>=2.5.2",
    "mcrcon>=0.7.0",
    "openai>=1.93.1",
    "python-dotenv>=1.1.1",
]
